name: CI

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7]

on:
  push:
    branches:
      - master
    paths:
    - '*.ipynb'
    run: echo "You have changed the source code!"
